# Generated by Django 5.2.5 on 2025-12-25 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('NOT_PICKED_UP', 'Not Picked Up'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('OUT_FOR_DELIVERY', 'Out For Delivery'), ('DELIVERED', 'Delivered')], default='NOT_PICKED_UP', max_length=30)),
                ('pickup_address', models.TextField()),
                ('pickup_contact_name', models.CharField(max_length=100)),
                ('pickup_contact_phone', models.CharField(max_length=20)),
                ('delivery_address', models.TextField()),
                ('delivery_recipient_name', models.CharField(max_length=100)),
                ('delivery_recipient_phone', models.CharField(max_length=20)),
                ('weight_range', models.CharField(choices=[('0-1kg', '0 – 1 kg'), ('1-2kg', '1 – 2 kg'), ('2-5kg', '2 – 5 kg'), ('5-10kg', '5 – 10 kg'), ('10kg+', '10 kg and above')], max_length=10)),
                ('package_type', models.CharField(choices=[('document', 'Document'), ('parcel', 'Parcel'), ('fragile', 'Fragile'), ('food', 'Food'), ('electronics', 'Electronics'), ('other', 'Other')], max_length=20)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
