# Generated by Django 5.2.5 on 2025-12-27 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packagemanagerapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagedelivery',
            options={'ordering': ['-created_at'], 'verbose_name': 'Package Delivery', 'verbose_name_plural': 'Package Deliveries'},
        ),
        migrations.AddField(
            model_name='packagedelivery',
            name='guest_email',
            field=models.EmailField(blank=True, help_text='Email for tracking (required for guest users)', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='packagedelivery',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_deliveries', to=settings.AUTH_USER_MODEL),
        ),
    ]
