# Generated by Django 5.2.5 on 2025-12-27 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packagemanagerapp', '0002_alter_packagedelivery_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagedelivery',
            name='guest_email',
        ),
    ]
