# Generated by Django 5.2.5 on 2025-12-27 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packagemanagerapp', '0003_remove_packagedelivery_guest_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagedelivery',
            name='tracking_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
