# Generated by Django 5.2.5 on 2025-12-27 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packagemanagerapp', '0004_alter_packagedelivery_tracking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagedelivery',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='packagedelivery',
            name='tracking_id',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
