# Generated by Django 5.2.5 on 2025-12-29 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packagemanagerapp', '0006_deliverystatushistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('shipping_type', models.CharField(choices=[('document', 'Document'), ('package', 'Package')], max_length=10)),
                ('shipping_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('quoted', 'Quoted'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('from_country', models.CharField(max_length=100)),
                ('from_state', models.CharField(max_length=100)),
                ('from_city', models.CharField(max_length=100)),
                ('from_street', models.CharField(max_length=255)),
                ('from_house_number', models.CharField(max_length=50)),
                ('from_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('to_country', models.CharField(max_length=100)),
                ('to_state', models.CharField(max_length=100)),
                ('to_city', models.CharField(max_length=100)),
                ('to_street', models.CharField(max_length=255)),
                ('to_house_number', models.CharField(max_length=50)),
                ('to_phone', models.CharField(max_length=20)),
                ('length_cm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('width_cm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('height_cm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_pieces', models.IntegerField()),
                ('estimated_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculated estimated fee', max_digits=10, null=True)),
                ('admin_quoted_price', models.DecimalField(blank=True, decimal_places=2, help_text="Admin's final quoted price", max_digits=10, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('quoted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quoted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes_provided', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_quotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='packagemana_user_id_49892c_idx'), models.Index(fields=['quote_reference'], name='packagemana_quote_r_9e36c8_idx'), models.Index(fields=['status'], name='packagemana_status_90d594_idx')],
            },
        ),
    ]
