# Generated by Django 5.2.5 on 2025-12-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packagemanagerapp', '0007_shippingquote'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='shippingquote',
            name='packagemana_user_id_49892c_idx',
        ),
        migrations.RemoveIndex(
            model_name='shippingquote',
            name='packagemana_quote_r_9e36c8_idx',
        ),
        migrations.RemoveIndex(
            model_name='shippingquote',
            name='packagemana_status_90d594_idx',
        ),
        migrations.RemoveField(
            model_name='shippingquote',
            name='admin_notes',
        ),
        migrations.RemoveField(
            model_name='shippingquote',
            name='admin_quoted_price',
        ),
        migrations.RemoveField(
            model_name='shippingquote',
            name='from_city',
        ),
        migrations.RemoveField(
            model_name='shippingquote',
            name='from_country',
        ),
        migrations.RemoveField(
            model_name='shippingquote',
            name='from_house_number',
        ),
        migrations.RemoveField(
            model_name='shippingquote',
            name='from_state',
        ),
        migrations.RemoveField(
            model_name='shippingquote',
            name='from_street',
        ),
        migrations.RemoveField(
            model_name='shippingquote',
            name='quoted_at',
        ),
        migrations.RemoveField(
            model_name='shippingquote',
            name='quoted_by',
        ),
        migrations.RemoveField(
            model_name='shippingquote',
            name='to_city',
        ),
        migrations.RemoveField(
            model_name='shippingquote',
            name='to_country',
        ),
        migrations.RemoveField(
            model_name='shippingquote',
            name='to_house_number',
        ),
        migrations.RemoveField(
            model_name='shippingquote',
            name='to_state',
        ),
        migrations.RemoveField(
            model_name='shippingquote',
            name='to_street',
        ),
        migrations.AddField(
            model_name='shippingquote',
            name='from_address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingquote',
            name='to_address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shippingquote',
            name='estimated_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
