# Generated by Django 5.2.5 on 2025-12-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packagemanagerapp', '0008_remove_shippingquote_packagemana_user_id_49892c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagedelivery',
            name='receiverCompanyName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='packagedelivery',
            name='senderCompanyName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
