# Generated by Django 5.2.5 on 2026-01-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packagemanagerapp', '0010_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagedelivery',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('pod', 'POD')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagedelivery',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
