# Generated by Django 5.2.5 on 2026-01-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packagemanagerapp', '0011_packagedelivery_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagedelivery',
            name='addons_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='packagedelivery',
            name='base_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='packagedelivery',
            name='delivery_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='packagedelivery',
            name='delivery_speed',
            field=models.CharField(choices=[('standard', 'Standard (3-6 hours)'), ('express', 'Express (1-2 hours)'), ('instant', 'Instant (Less than 1 hour)')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='packagedelivery',
            name='distance_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='packagedelivery',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='packagedelivery',
            name='fragile_handling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='packagedelivery',
            name='oversized_package',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='packagedelivery',
            name='signature_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='packagedelivery',
            name='speed_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='packagedelivery',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('pod', 'POD')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='packagedelivery',
            name='weight_range',
            field=models.CharField(choices=[('1-5kg', '1 – 5 kg'), ('5-15kg', '5 – 15 kg'), ('15-30kg', '15 – 30 kg'), ('30kg+', '30 kg and above')], max_length=10),
        ),
    ]
