# Generated by Django 5.2.5 on 2026-01-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packagemanagerapp', '0012_packagedelivery_addons_fee_packagedelivery_base_fee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingquote',
            options={'ordering': ['-created_at'], 'verbose_name': 'Shipping Quote', 'verbose_name_plural': 'Shipping Quotes'},
        ),
        migrations.RenameField(
            model_name='shippingquote',
            old_name='to_address',
            new_name='delivery_address',
        ),
        migrations.RenameField(
            model_name='shippingquote',
            old_name='estimated_fee',
            new_name='delivery_fee',
        ),
        migrations.RenameField(
            model_name='shippingquote',
            old_name='to_phone',
            new_name='delivery_recipient_phone',
        ),
        migrations.RenameField(
            model_name='shippingquote',
            old_name='from_address',
            new_name='pickup_address',
        ),
        migrations.RemoveField(
            model_name='shippingquote',
            name='from_phone',
        ),
        migrations.RemoveField(
            model_name='shippingquote',
            name='height_cm',
        ),
        migrations.RemoveField(
            model_name='shippingquote',
            name='length_cm',
        ),
        migrations.RemoveField(
            model_name='shippingquote',
            name='number_of_pieces',
        ),
        migrations.RemoveField(
            model_name='shippingquote',
            name='shipping_date',
        ),
        migrations.RemoveField(
            model_name='shippingquote',
            name='shipping_type',
        ),
        migrations.RemoveField(
            model_name='shippingquote',
            name='weight_kg',
        ),
        migrations.RemoveField(
            model_name='shippingquote',
            name='width_cm',
        ),
        migrations.AddField(
            model_name='shippingquote',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingquote',
            name='addons_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shippingquote',
            name='base_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shippingquote',
            name='delivery_recipient_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingquote',
            name='delivery_speed',
            field=models.CharField(choices=[('standard', 'Standard (3-6 hours)'), ('express', 'Express (1-2 hours)'), ('instant', 'Instant (Less than 1 hour)')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='shippingquote',
            name='distance_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shippingquote',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shippingquote',
            name='fragile_handling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shippingquote',
            name='oversized_package',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shippingquote',
            name='package_type',
            field=models.CharField(choices=[('document', 'Document'), ('parcel', 'Parcel'), ('fragile', 'Fragile'), ('food', 'Food'), ('electronics', 'Electronics'), ('other', 'Other')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingquote',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('pod', 'POD')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shippingquote',
            name='pickup_contact_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingquote',
            name='pickup_contact_phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingquote',
            name='receiverCompanyName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shippingquote',
            name='senderCompanyName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shippingquote',
            name='signature_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shippingquote',
            name='speed_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shippingquote',
            name='weight_range',
            field=models.CharField(choices=[('1-5kg', '1 – 5 kg'), ('5-15kg', '5 – 15 kg'), ('15-30kg', '15 – 30 kg'), ('30kg+', '30 kg and above')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='packagedelivery',
            name='payment_status',
            field=models.CharField(blank=True, default='Pending', max_length=100, null=True),
        ),
    ]
