# Generated by Django 5.2.5 on 2026-01-06 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packagemanagerapp', '0013_alter_shippingquote_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagedelivery',
            name='delivery_recipient_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
