# Generated by Django 5.2.5 on 2026-01-09 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packagemanagerapp', '0016_merchantnotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagedelivery',
            options={'ordering': ['-edited_at'], 'verbose_name': 'Package Delivery', 'verbose_name_plural': 'Package Deliveries'},
        ),
        migrations.CreateModel(
            name='BulkShipmentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulk_tracking_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('PROCESSING', 'Processing'), ('PAID', 'Paid'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30)),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='bulk_shipments/')),
                ('total_shipments', models.IntegerField(default=0)),
                ('valid_shipments', models.IntegerField(default=0)),
                ('invalid_shipments', models.IntegerField(default=0)),
                ('total_delivery_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_base_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_distance_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_speed_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_addons_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_status', models.CharField(default='Pending', max_length=100)),
                ('payment_method', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_shipment_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulk Shipment Upload',
                'verbose_name_plural': 'Bulk Shipment Uploads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VALID', 'Valid'), ('INVALID', 'Invalid'), ('NOT_PICKED_UP', 'Not Picked Up'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('OUT_FOR_DELIVERY', 'Out For Delivery'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=30)),
                ('row_number', models.IntegerField()),
                ('receiver_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('delivery_address', models.TextField()),
                ('postal_code', models.CharField(max_length=20)),
                ('weight_range', models.CharField(choices=[('1-5kg', '1 – 5 kg'), ('5-15kg', '5 – 15 kg'), ('15-30kg', '15 – 30 kg'), ('30kg+', '30 kg and above')], max_length=10)),
                ('pickup_address', models.TextField(blank=True, null=True)),
                ('pickup_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pickup_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('delivery_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('base_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('distance_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('speed_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('addons_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('validation_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bulk_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_items', to='packagemanagerapp.bulkshipmentupload')),
            ],
            options={
                'verbose_name': 'Bulk Shipment Item',
                'verbose_name_plural': 'Bulk Shipment Items',
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='PickupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(choices=[('single', 'Single Shipment'), ('bulk', 'Bulk Shipment')], max_length=10)),
                ('delivery_type', models.CharField(choices=[('same-day', 'Same Day'), ('next-day', 'Next Day'), ('custom', 'Custom')], max_length=10)),
                ('custom_date', models.DateField(blank=True, null=True)),
                ('pickup_time_slot', models.CharField(choices=[('morning', 'Morning (8AM - 12PM)'), ('afternoon', 'Afternoon (12PM - 4PM)'), ('evening', 'Evening (4PM - 8PM)')], max_length=20)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('shipment_name', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_shipments', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
