# Generated by Django 5.2.5 on 2026-01-11 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packagemanagerapp', '0017_alter_packagedelivery_options_bulkshipmentupload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkshipmentupload',
            name='status',
            field=models.CharField(choices=[('NOT_PICKED_UP', 'Not Picked Up'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('OUT_FOR_DELIVERY', 'Out For Delivery'), ('DELIVERED', 'Delivered')], default='NOT_PICKED_UP', max_length=30),
        ),
    ]
