# Generated by Django 5.2.5 on 2026-01-11 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packagemanagerapp', '0018_alter_bulkshipmentupload_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagedelivery',
            name='package_type',
            field=models.CharField(choices=[('document', 'Document'), ('parcel', 'Parcel'), ('package', 'Package'), ('fragile', 'Fragile'), ('food', 'Food'), ('electronics', 'Electronics'), ('other', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='IssueFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('issue_type', models.CharField(choices=[('package_not_delivered', 'Package not delivered'), ('package_damaged', 'Package damaged'), ('wrong_item_received', 'Wrong item received'), ('tracking_issues', 'Tracking issues'), ('payment_issues', 'Payment issues'), ('pickup_not_completed', 'Pickup not completed'), ('driver_behaviour_concern', 'Driver behaviour concern'), ('other', 'Other')], max_length=50)),
                ('tracking_id', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='feedback_files/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_response', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Issue Feedback',
                'verbose_name_plural': 'Issue Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
