# Generated by Django 5.2.5 on 2026-01-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packagemanagerapp', '0019_alter_packagedelivery_package_type_issuefeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuefeedback',
            name='issue_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
