# Generated by Django 5.2.5 on 2025-12-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='emailVerificationStatus',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
