# Generated by Django 5.2.5 on 2026-01-10 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_alalaxadmin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='merchant_profiles/'),
        ),
        migrations.CreateModel(
            name='MerchantAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='onboarding.merchantprofile')),
            ],
        ),
    ]
